version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    links:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
